"""JSON 原子能力可以绑定的最小执行语义。"""

from __future__ import annotations

from types import MappingProxyType

EXECUTOR_CATEGORIES = MappingProxyType(
    {
        "装配属性": frozenset({"装配"}),
        "装配规则": frozenset({"装配"}),
        "装配主动技能": frozenset({"装配"}),
        "装配被动技能": frozenset({"装配"}),
        "顺序执行": frozenset({"组合"}),
        "条件执行": frozenset({"组合"}),
        "随机执行": frozenset({"组合"}),
        "遍历目标": frozenset({"组合"}),
        "重复执行": frozenset({"组合"}),
        "尝试执行": frozenset({"组合"}),
        "事务执行": frozenset({"组合"}),
        "监听事件": frozenset({"触发"}),
        "读取数值": frozenset({"数值"}),
        "计算数值": frozenset({"数值"}),
        "随机数值": frozenset({"数值"}),
        "聚合数值": frozenset({"数值"}),
        "选择目标": frozenset({"目标"}),
        "选择技能": frozenset({"目标"}),
        "选择状态": frozenset({"目标"}),
        "概率条件": frozenset({"条件"}),
        "数值条件": frozenset({"条件"}),
        "状态条件": frozenset({"条件"}),
        "类型条件": frozenset({"条件"}),
        "组合条件": frozenset({"条件"}),
        "标签条件": frozenset({"条件"}),
        "造成伤害": frozenset({"效果"}),
        "恢复资源": frozenset({"效果"}),
        "消耗资源": frozenset({"效果"}),
        "支付代价": frozenset({"效果"}),
        "设置资源": frozenset({"效果"}),
        "转移资源": frozenset({"效果"}),
        "添加状态": frozenset({"效果"}),
        "移除状态": frozenset({"效果"}),
        "修改状态层数": frozenset({"效果"}),
        "修改状态持续": frozenset({"效果"}),
        "复制状态": frozenset({"效果"}),
        "转移状态": frozenset({"效果"}),
        "修改行动条": frozenset({"效果"}),
        "修改技能冷却": frozenset({"效果"}),
        "修改构筑计量": frozenset({"效果"}),
        "追加攻击": frozenset({"效果"}),
        "分摊伤害": frozenset({"效果"}),
        "转移伤害": frozenset({"效果"}),
        "抵挡致命伤害": frozenset({"效果"}),
        "复活": frozenset({"效果"}),
        "修改事件数值": frozenset({"效果"}),
        "修改事件目标": frozenset({"效果"}),
        "修改事件标签": frozenset({"效果"}),
        "取消事件": frozenset({"效果"}),
        "触发技能": frozenset({"效果"}),
        "记录战斗事实": frozenset({"效果"}),
        "修改战斗关联": frozenset({"效果"}),
        "修改技能": frozenset({"效果"}),
        "复制技能": frozenset({"效果"}),
        "修改行动意图": frozenset({"效果"}),
        "转化事件": frozenset({"效果"}),
        "修改判定": frozenset({"效果"}),
        "修改战场规则": frozenset({"效果"}),
        "保存结果": frozenset({"效果"}),
        "切换形态": frozenset({"效果"}),
        "创建战斗对象": frozenset({"效果"}),
        "移除战斗对象": frozenset({"效果"}),
        "修改归属": frozenset({"效果"}),
        "回放效果": frozenset({"效果"}),
        "修改战术": frozenset({"效果"}),
    }
)
